### ISSUE TITLE
编译版本运行报错

### ISSUE THREAD

**Issue by zerorzeror** [0Chencc/CTFCrackTools#40]
下载编译版本，运行报错
F:\DownLoads\CTFcrackTools\CTFcrackTools>java -jar CTFCrackTools-4.0.6.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.ctfcracktools.json.PluginsJson.isJson(PluginsJson.kt:70)
        at org.ctfcracktools.json.PluginsJson.<init>(PluginsJson.kt:15)
        at org.ctfcracktools.ui.DecodePanel.<init>(DecodePanel.java:292)
        at org.ctfcracktools.ui.MainUi.initComponents(MainUi.java:41)
        at org.ctfcracktools.ui.MainUi.<init>(MainUi.java:24)
        at org.ctfcracktools.Main.main(Main.java:24)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.lang.Object.finalize() throws java.lang.Throwable accessible: module java.base does not "opens java.lang" to unnamed module @3ada9e37

F:\DownLoads\CTFcrackTools\CTFcrackTools>java --version
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

不知道是否java版本有关，还是使用方法不对？

**Comment by 0Chencc** [comment]
这个问题在[https://github.com/0Chencc/CTFCrackTools/issues/41#issuecomment-1317684103](https://github.com/0Chencc/CTFCrackTools/issues/41#issuecomment-1317684103)中得到解决
