### ISSUE TITLE
报错，Exception in thread "main" java.lang.ExceptionInInitializerError。

### ISSUE THREAD

**Issue by Crystron39** [0Chencc/CTFCrackTools#41]
没学过java帮不上啥忙，网上找到的内容看不懂（）
拜托大佬看一下
提示内容：
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.ctfcracktools.json.PluginsJson.isJson(PluginsJson.kt:70)
        at org.ctfcracktools.json.PluginsJson.<init>(PluginsJson.kt:15)
        at org.ctfcracktools.ui.DecodePanel.<init>(DecodePanel.java:292)
        at org.ctfcracktools.ui.MainUi.initComponents(MainUi.java:41)
        at org.ctfcracktools.ui.MainUi.<init>(MainUi.java:24)
        at org.ctfcracktools.Main.main(Main.java:24)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.lang.Object.finalize() throws java.lang.Throwable accessible: module java.base does not "opens java.lang" to unnamed module @59690aa4
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
        at org.python.core.PyJavaType.init(PyJavaType.java:475)
        at org.python.core.PyType$Registry.createType(PyType.java:477)
        at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
        at org.python.core.PyType$Registry.resolveType(PyType.java:352)
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at org.python.core.PyType.fromClass(PyType.java:2137)
        at org.python.core.PyObject.<init>(PyObject.java:85)
        at org.python.core.PyJavaPackage.<init>(PyJavaPackage.java:36)
        at org.python.core.PyJavaPackage.<init>(PyJavaPackage.java:33)
        at org.python.core.packagecache.PackageManager.<init>(PackageManager.java:30)
        at org.python.core.packagecache.CachedJarsPackageManager.<init>(CachedJarsPackageManager.java:45)
        at org.python.core.packagecache.PathPackageManager.<init>(PathPackageManager.java:30)
        at org.python.core.packagecache.SysPackageManager.<init>(SysPackageManager.java:57)
        at org.python.core.PySystemState.initPackages(PySystemState.java:1288)
        at org.python.core.PySystemState.doInitialize(PySystemState.java:1213)
        at org.python.core.PySystemState.initialize(PySystemState.java:1130)
        at org.python.core.PySystemState.initialize(PySystemState.java:1085)
        at org.python.core.PySystemState.initialize(PySystemState.java:1080)
        at org.python.util.PythonInterpreter.initialize(PythonInterpreter.java:63)
        at org.ctfcracktools.fuction.PythonFunc.jythonLoad(PythonFunc.kt:30)
        at org.ctfcracktools.fuction.PythonFunc.<init>(PythonFunc.kt:16)
        at org.ctfcracktools.Config.<clinit>(Config.java:23)
        ... 6 more

**Comment by 0Chencc** [comment]
方便贴一下您的java版本吗

**Comment by Crystron39** [comment]
> 



> 方便贴一下您的java版本吗

openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
 
麻烦您了

**Comment by Crystron39** [comment]
> 方便贴一下您的java版本吗

非常抱歉，这段时间没看消息

**Comment by Crystron39** [comment]
试了一下，4.0.3是可以用的，后面的版本就用不了了

**Comment by 0Chencc** [comment]
定位到问题了，下个版本修复

**Comment by 0Chencc** [comment]
是由于插件模块需要java.lang这个包的反射APi调用权限，具体参考了[how-to-solve-inaccessibleobjectexception](https://stackoverflow.com/questions/41265266/how-to-solve-inaccessibleobjectexception-unable-to-make-member-accessible-m)这个讨论
可以尝试使用以下命令执行本程序
```shell
java -jar CTFCrackTools-4.0.6.jar --add-opens java.base/java.lang=ALL-UNNAMED
```
不过奇怪的是我在mac下使用11并没有遇到这个问题，我后续思考一下如何更好的解决这个问题
